/* Automatically generated by
	CCodeGenerator VMMaker.oscog-nice.2580 uuid: 80ed6059-062f-4907-843c-7ae7d21d86aa
 */

typedef struct {
	sqInt	classTag;
	sqInt	enclosingObject;
	sqInt	target;
	sqInt	selector;
	sqInt	numArgs;
	sqInt	depth;
 } NSSendCache;
